### ISSUE TITLE
[REQUEST] Getting most dominant color and putting it.

### ISSUE THREAD

**Issue by rbcetin** [augustinbegue/icue-ambilight#26]
To get a homogenous view I think it would be good to get the most dominant color and just put it. Just like philips hue.

**Comment by Tagueo** [comment]
Hi, I could implement this as a second selectable behavior. I'll look into it.

**Comment by gerbenvandijk** [comment]
I'd like to second this request 👍

**Comment by Tagueo** [comment]
I'll definitely implement it in a coming release, I just need to find some time x), but I really like the idea and the improvements it could bring.
