### ISSUE TITLE
[REQUEST] change leds canvas

### ISSUE THREAD

**Issue by StrykeZ99** [augustinbegue/icue-ambilight#35]
Hello,
First of all, great project!
When using Ambilight, it only uses a very narrow led canvas on the bottom of my screen. So, I was wondering if it is possible to change that to, for example, a section of your screen as shown in your youtube video.
![Untitled](https://user-images.githubusercontent.com/86617122/123666312-62f6a980-d839-11eb-9f15-7b148589aec1.png)
Love the good work!

**Comment by augustinbegue** [comment]
Hi!
To begin, sorry for the extreme inactivity, school is giving me a hard time to find some free time 🙃...

Currently, the screen is mapped to the position of the leds. A more logical behaviour would be indeed to map the position of the leds to the screen to allow for more flexibility in the Layout tab. I'll implement this when I rewrite it.

Thanks for making your request!
