### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by severd8** [augustinbegue/icue-ambilight#38]
**Describe the bug**
Over time, icue-ambilight.exe increases in memory to the point in which I need to restart it. Last night, it peaked at about 10GB of memory usage. It's currently at 1.8GB.

![image](https://user-images.githubusercontent.com/44451903/127786686-a5b78eee-6f06-4aca-b852-02e59d8a76f4.png)

Let me know if any other info is needed from me.

**Comment by Extremyoshi** [comment]
I have the same problem. I think it started to happen after an windows update.

**Comment by chriiis78** [comment]
I'm kinda noob about Electron and all its stuff. But I searched the leak for a while and only thing I observed is that if we don't put the screen native resolution in parameters of navigator.mediaDevices.getUserMedia, it causes memory leak.

For exemple, my screen is 1920*1080, so :
- minWidth and maxWidth : 1920
- minHeight and maxHeight : 1080

https://github.com/augustinbegue/icue-ambilight/blob/fab5931efd260594089b6ab8d9563060583d208d/src/capture/index.js#L24

**Comment by Extremyoshi** [comment]
> I'm kinda noob about Electron and all its stuff. But I searched the leak for a while and only thing I observed is that if we don't put the screen native resolution in parameters of navigator.mediaDevices.getUserMedia, it causes memory leak.
> 
> For exemple, my screen is 1920*1080, so :
> 
> * minWidth and maxWidth : 1920
> * minHeight and maxHeight : 1080
> 
> https://github.com/augustinbegue/icue-ambilight/blob/fab5931efd260594089b6ab8d9563060583d208d/src/capture/index.js#L24

I cant seem to find the config file to edit the parameters. Do I have to do this before or after the installation?
