### ISSUE TITLE
[BUG] Nothing is Working for me after Update V1.6.3

### ISSUE THREAD

**Issue by xLMDCx** [augustinbegue/icue-ambilight#54]
Ive installed the new Update and nothing worked anymore. After a clean Reinstall with deleting files in Roaming it still wont work, Boxes are there, Devices are shown, but not controlled. Even the little Box "Show LEDs" wont show any LEDs on the screen.

Reinstalled the older Release V1.6.2 and everything worked just fine as before

![iCue Ambilight 28 12 2021 12_24_21](https://user-images.githubusercontent.com/76822327/147563850-d83c5391-4b66-498b-b39c-15756152729c.png)
.

**Comment by augustinbegue** [comment]
Hi, I've been able to reproduce the issue and it should be fixed in the next release. Thanks for reporting it!
